# Generated by Django 3.1.7 on 2021-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('card_no', models.CharField(max_length=16)),
                ('color', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry', models.CharField(max_length=5)),
            ],
        ),
    ]
